# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeimentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField()),
                ('wait_for_answers', models.BooleanField()),
                ('time', models.IntegerField()),
                ('training_length', models.IntegerField()),
                ('session_count', models.IntegerField()),
                ('session_length', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('message1', models.CharField(max_length=1023)),
                ('message2', models.CharField(max_length=1023)),
                ('message3', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExpeimentDefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.IntegerField()),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExperimentInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Session')),
            ],
        ),
        migrations.AddField(
            model_name='press',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Test'),
        ),
    ]
