# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160123_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdefinition',
            name='message4',
            field=models.CharField(default='Koniec eksperymentu, dziekujemy!', max_length=1023),
        ),
        migrations.AlterField(
            model_name='experimentdefinition',
            name='message1',
            field=models.CharField(default='Witaj w eksperymencie!', max_length=1023),
        ),
        migrations.AlterField(
            model_name='experimentdefinition',
            name='message2',
            field=models.CharField(default='Koniec treningu!', max_length=1023),
        ),
        migrations.AlterField(
            model_name='experimentdefinition',
            name='message3',
            field=models.CharField(default='Koniec sesji!', max_length=1023),
        ),
    ]
