# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160124_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentinstance',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
