# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160124_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
