# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160202_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
